FROM mongo:7

COPY db/filmes.json  /docker-entrypoint-initdb.d/
COPY db/atores.json  /docker-entrypoint-initdb.d/
COPY db/generos.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/import.sh
RUN chmod +x /docker-entrypoint-initdb.d/import.sh