services:
  mongodb:
    build:
      context: ./ex1/api_dados
      dockerfile: Dockerfile.mongo
    container_name: mongodb_repairs
    networks:
      - ew2026-network

  api:
    build: 
      context: ./ex1/api_dados
      dockerfile: Dockerfile # O teu servidor de API minimalista
    container_name: api_dados_repairs
    ports:
      - "16025:16025"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/autoRepair
    depends_on:
      - mongodb
    networks:
      - ew2026-network

  interface:
    build:
      context: ./ex2/interface
      dockerfile: Dockerfile.interface # Dockerfile para este novo servidor
    container_name: interface_web
    ports:
      - "16026:16026"
    environment:
      - API_URL=http://api_dados_repairs:16025
    depends_on:
      - api
    networks:
      - ew2026-network

networks:
  ew2026-network:
    driver: bridge